node
{
    stage('checkout code')
    {
    checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'git', url: 'https://github.com/lturaga/project1.git']]]
    
    }
    stage('get project code')
    {
        dir('job3') {
          git changelog: false, poll: false, url: 'https://github.com/edureka-devops/projCert.git'
       }  
     }
}
