node('slave')
{
    stage('checkout code')
    {
    checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'git', url: 'https://github.com/lturaga/project1.git']]]
    
    }
    stage('get project code')
    {
        dir('job3') {
            
          
          sh 'sudo docker build -t lturaga/webapp .'
          sh 'sudo docker run -it -d --name webapp -p 80:80 lturaga/webapp'
          //sh 'num=`sudo docker container ps | grep webapp | wc -l`'
          
       }  
     }
}
