node{
	stage('checkout code')
	{
		checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'git', url: 'https://github.com/lturaga/project1.git']]]

	}
	
	stage('execute playbook')
	{
		sh 'cd ${WORKSPACE}/job2 && ansible-playbook -i ${WORKSPACE}/job2/hosts.yaml ${WORKSPACE}/job2/docker-playbook.yaml -u ubuntu'
	}
}
